from typing import Optional, List
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_, func
from sqlalchemy.orm import selectinload

from app.models.client_model import Client
from app.models.client_whatsapp_credential import ClientWhatsAppCredential
from app.schemas.client_schema import ClientCreate, ClientUpdate, ClientCreateWithPassword
from app.core.security import hash_password, verify_password
import logging

logger = logging.getLogger(__name__)

# Fields that must never be set to None via an update payload
_REQUIRED_FIELDS = {"merchant_id", "id", "name"}


class ClientService:
    def __init__(self, db: AsyncSession):
        if not db:
            raise ValueError("AsyncSession must be provided")
        self.db = db

    # -----------------------------
    # INTERNAL: Generate Store ID
    # -----------------------------
    async def _generate_store_id(self) -> str:
        """
        Auto-generate the next sequential Store ID (e.g. ST0001, ST0002).
        Scans existing IDs with the ST prefix and finds the next available slot.
        Falls back to a random suffix if the sequential scan exhausts 100 attempts.
        """
        result = await self.db.execute(select(func.count(Client.id)))
        count = result.scalar() or 0
        for n in range(count + 1, count + 200):
            candidate = f"ST{n:04d}"
            exists = await self.db.execute(
                select(Client.id).where(Client.id == candidate)
            )
            if not exists.scalar_one_or_none():
                return candidate
        import secrets
        return f"ST{secrets.randbelow(9000) + 1000}"

    # -----------------------------
    # CREATE
    # -----------------------------
    async def create(self, data: ClientCreate) -> Optional[Client]:
        """Create a new client"""
        result = await self.db.execute(
            select(Client).where(
                and_(
                    Client.id == data.id,
                    Client.merchant_id == data.merchant_id,
                )
            )
        )
        if result.scalars().first():
            return None

        client = Client(
            id=data.id,
            name=data.name,
            whatsapp_number=data.whatsapp_number,
            store_contact_number=data.store_contact_number,
            merchant_id=data.merchant_id,
        )

        self.db.add(client)
        await self.db.commit()
        await self.db.refresh(client)
        return client

    # -----------------------------
    # CREATE WITH PASSWORD
    # -----------------------------
    async def create_with_password(
        self,
        merchant_id: str,
        payload: ClientCreateWithPassword,
    ) -> Optional[Client]:
        """
        Merchant-initiated store creation with a dashboard password.
        Called from POST /clients/with-password/.
        The Store ID is auto-generated by the system — merchants do not choose it.
        The generated ID is returned on the client object so the API layer
        can include it in the confirmation email.
        Returns None only on an unexpected collision (extremely rare).
        """
        store_id = await self._generate_store_id()

        # Collision guard (should never happen in normal usage)
        exists = await self.db.execute(
            select(Client).where(Client.id == store_id)
        )
        if exists.scalars().first():
            logger.error("Store ID collision on auto-generated ID: %s", store_id)
            return None

        client = Client(
            id=store_id,
            name=payload.name,
            merchant_id=merchant_id,
            whatsapp_number=payload.whatsapp_number,
            password_hash=hash_password(payload.password),
        )

        self.db.add(client)
        await self.db.commit()
        await self.db.refresh(client)
        return client

    # -----------------------------
    # AUTHENTICATE (store login)
    # -----------------------------
    async def authenticate(
        self,
        client_id: str,
        password: str,
    ) -> Optional[Client]:
        """
        Verify store login credentials.
        Returns the Client on success, None on failure (wrong ID, no password set,
        or wrong password).
        """
        result = await self.db.execute(
            select(Client).where(Client.id == client_id)
        )
        client = result.scalars().first()

        if not client:
            return None
        if not client.password_hash:
            # Store exists but no password configured yet
            return None
        if not verify_password(password, client.password_hash):
            return None

        return client

    # -----------------------------
    # SET / RESET PASSWORD
    # -----------------------------
    async def set_password(
        self,
        client_id: str,
        password: str,
        merchant_id: Optional[str] = None,
    ) -> Optional[Client]:
        """
        Set or reset the dashboard password for a store.
        Merchant-only action — always pass merchant_id to scope the lookup.
        """
        client = await self.get(client_id, merchant_id=merchant_id, include_credential=False)
        if not client:
            return None

        client.password_hash = hash_password(password)
        await self.db.commit()
        await self.db.refresh(client)
        return client

    # -----------------------------
    # GET (merchant-scoped)
    # -----------------------------
    async def get(
        self,
        client_id: str,
        merchant_id: Optional[str] = None,
        include_credential: bool = True
    ) -> Optional[Client]:
        """Get client by ID, optionally including credential"""
        stmt = select(Client).where(Client.id == client_id)

        if include_credential:
            stmt = stmt.options(selectinload(Client.whatsapp_credential))

        if merchant_id:
            stmt = stmt.where(Client.merchant_id == merchant_id)

        result = await self.db.execute(stmt)
        return result.scalars().first()

    # -----------------------------
    # LIST (merchant-scoped)
    # -----------------------------
    async def list_all(
        self,
        merchant_id: str,
        skip: int = 0,
        limit: int = 100,
        has_credential: Optional[bool] = None
    ) -> List[Client]:
        """List clients with optional filters"""
        stmt = select(Client).where(Client.merchant_id == merchant_id)
        stmt = stmt.options(selectinload(Client.whatsapp_credential))

        if has_credential is not None:
            if has_credential:
                stmt = stmt.where(Client.whatsapp_credential != None)
            else:
                stmt = stmt.where(Client.whatsapp_credential == None)

        stmt = stmt.offset(skip).limit(limit).order_by(Client.created_at.desc())
        result = await self.db.execute(stmt)
        return result.scalars().all()

    # -----------------------------
    # UPDATE
    # -----------------------------
    async def update(
        self,
        client_id: str,
        payload: ClientUpdate,
        merchant_id: Optional[str] = None,
    ) -> Optional[Client]:
        """Update client information"""
        client = await self.get(client_id, merchant_id, include_credential=False)
        if not client:
            return None

        update_data = payload.model_dump(exclude_unset=True)
        update_data.pop("merchant_id", None)
        update_data.pop("id", None)

        for key, value in update_data.items():
            if value is None and key in _REQUIRED_FIELDS:
                continue
            setattr(client, key, value)

        await self.db.commit()
        await self.db.refresh(client)
        return client

    # -----------------------------
    # DELETE
    # -----------------------------
    async def delete(
        self,
        client_id: str,
        merchant_id: Optional[str] = None,
    ) -> bool:
        """Delete a client (cascades to credential)"""
        client = await self.get(client_id, merchant_id, include_credential=False)
        if not client:
            return False

        await self.db.delete(client)
        await self.db.commit()
        return True

    # -----------------------------
    # CREDENTIAL MANAGEMENT (1:1)
    # -----------------------------

    async def get_credential(
        self,
        client_id: str,
        merchant_id: Optional[str] = None,
    ) -> Optional[ClientWhatsAppCredential]:
        """Get WhatsApp credential for a client"""
        client = await self.get(client_id, merchant_id, include_credential=True)
        if not client:
            return None
        return client.whatsapp_credential

    async def create_credential(
        self,
        client_id: str,
        credential_data: dict,
        merchant_id: Optional[str] = None,
    ) -> Optional[ClientWhatsAppCredential]:
        """Create WhatsApp credential for a client"""
        client = await self.get(client_id, merchant_id, include_credential=True)
        if not client:
            return None

        if client.whatsapp_credential:
            logger.warning(f"Client {client_id} already has a WhatsApp credential")
            return None

        existing_phone = await self.db.execute(
            select(ClientWhatsAppCredential).where(
                ClientWhatsAppCredential.phone_number_id == credential_data.get("phone_number_id")
            )
        )
        if existing_phone.scalars().first():
            logger.warning(f"Duplicate phone_number_id: {credential_data.get('phone_number_id')}")
            return None

        whatsapp_number = credential_data.get("whatsapp_number")
        if whatsapp_number:
            existing_whatsapp = await self.db.execute(
                select(ClientWhatsAppCredential).where(
                    ClientWhatsAppCredential.whatsapp_number == whatsapp_number
                )
            )
            if existing_whatsapp.scalars().first():
                logger.warning(f"Duplicate whatsapp_number: {whatsapp_number}")
                return None

        credential = ClientWhatsAppCredential(client_id=client_id, **credential_data)
        self.db.add(credential)
        await self.db.commit()
        await self.db.refresh(credential)
        return credential

    async def update_credential(
        self,
        client_id: str,
        credential_data: dict,
        merchant_id: Optional[str] = None,
    ) -> Optional[ClientWhatsAppCredential]:
        """Update WhatsApp credential for a client"""
        client = await self.get(client_id, merchant_id, include_credential=True)
        if not client or not client.whatsapp_credential:
            return None

        credential = client.whatsapp_credential

        new_phone_id = credential_data.get("phone_number_id")
        if new_phone_id and new_phone_id != credential.phone_number_id:
            existing = await self.db.execute(
                select(ClientWhatsAppCredential).where(
                    ClientWhatsAppCredential.phone_number_id == new_phone_id,
                    ClientWhatsAppCredential.client_id != client_id
                )
            )
            if existing.scalars().first():
                logger.warning(f"Duplicate phone_number_id: {new_phone_id}")
                return None

        new_whatsapp = credential_data.get("whatsapp_number")
        if new_whatsapp and new_whatsapp != credential.whatsapp_number:
            existing = await self.db.execute(
                select(ClientWhatsAppCredential).where(
                    ClientWhatsAppCredential.whatsapp_number == new_whatsapp,
                    ClientWhatsAppCredential.client_id != client_id
                )
            )
            if existing.scalars().first():
                logger.warning(f"Duplicate whatsapp_number: {new_whatsapp}")
                return None

        for key, value in credential_data.items():
            if value is not None:
                setattr(credential, key, value)

        await self.db.commit()
        await self.db.refresh(credential)
        return credential

    async def delete_credential(
        self,
        client_id: str,
        merchant_id: Optional[str] = None,
    ) -> bool:
        """Delete WhatsApp credential for a client"""
        client = await self.get(client_id, merchant_id, include_credential=True)
        if not client or not client.whatsapp_credential:
            return False

        await self.db.delete(client.whatsapp_credential)
        await self.db.commit()
        return True

    # -----------------------------
    # HELPER METHODS
    # -----------------------------

    async def has_active_credential(
        self,
        client_id: str,
        merchant_id: Optional[str] = None,
    ) -> bool:
        """Check if client has an active WhatsApp credential"""
        credential = await self.get_credential(client_id, merchant_id)
        return bool(credential and credential.active)

    async def count_clients_with_credentials(self, merchant_id: str) -> int:
        """Count how many clients have WhatsApp credentials"""
        result = await self.db.execute(
            select(Client)
            .join(ClientWhatsAppCredential, Client.id == ClientWhatsAppCredential.client_id)
            .where(Client.merchant_id == merchant_id)
            .where(ClientWhatsAppCredential.active == True)
        )
        return len(result.scalars().all())
