from pydantic import BaseModel, Field, ConfigDict
from typing import Optional
from datetime import datetime
import logging

from .client_whatsapp_credential import ClientWhatsAppCredentialSimple, ClientWhatsAppCredentialCreate

logger = logging.getLogger(__name__)


# =====================================================
# Base fields (shared)
# =====================================================
class ClientBase(BaseModel):
    id: str = Field(
        ...,
        min_length=8,
        max_length=8,
        pattern=r"^ST[A-Z0-9]{6}$",
        description="Client ID (ST + 6 alphanumeric chars)"
    )
    name: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Client name"
    )
    whatsapp_number: Optional[str] = Field(
        None,
        pattern=r'^\+\d{10,15}$',
        example="+2348012345678",
        description="Customer-facing WhatsApp number (E.164 format)"
    )
    store_contact_number: Optional[str] = Field(
        None,
        pattern=r'^\+\d{10,15}$',
        example="+2348098765432",
        description="Store contact number for order confirmation/pickup (E.164 format)"
    )
    merchant_id: str = Field(
        ...,
        min_length=8,
        max_length=8,
        pattern=r"^MX[A-Z0-9]{6}$",
        description="Merchant ID (MX + 6 alphanumeric chars)"
    )


# =====================================================
# Create (existing — untouched)
# =====================================================
class ClientCreate(ClientBase):
    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "id": "CL5678",
                "name": "Tech Store Lagos",
                "whatsapp_number": "+2348012345678",
                "store_contact_number": "+2348098765432",
                "merchant_id": "MR1234"
            }
        }
    )


# =====================================================
# Create with password — merchant "Add Store" flow
# The Store ID is now auto-assigned by the system.
# Merchants no longer choose their own ID.
# =====================================================
class ClientCreateWithPassword(BaseModel):
    """
    Used by the merchant dashboard "Add Store" modal.
    The Store ID is auto-generated by the system and sent to the merchant
    via email. Merchants do not supply their own ID.
    WhatsApp onboarding is handled separately by the admin.
    """
    name: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Store display name"
    )
    whatsapp_number: Optional[str] = Field(
        None,
        pattern=r'^\+\d{10,15}$',
        description="WhatsApp number — can be set later after onboarding"
    )
    password: str = Field(
        ...,
        min_length=6,
        description="Plain-text password for store dashboard login (min 6 chars)"
    )

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "name": "Lekki Branch",
                "whatsapp_number": "+2348012345678",
                "password": "securepass123"
            }
        }
    )


# =====================================================
# Update (all optional)
# =====================================================
class ClientUpdate(BaseModel):
    name: Optional[str] = Field(
        None,
        min_length=1,
        max_length=100,
        description="Client name"
    )
    whatsapp_number: Optional[str] = Field(
        None,
        pattern=r'^\+\d{10,15}$',
        description="Customer-facing WhatsApp number (E.164 format)"
    )
    store_contact_number: Optional[str] = Field(
        None,
        pattern=r'^\+\d{10,15}$',
        description="Store contact number (E.164 format)"
    )
    operator_notify_phone: Optional[str] = Field(
        None,
        description="Operator WhatsApp number for order/payment notifications (without +, e.g. 2348012345678)"
    )
    address: Optional[str] = Field(
        None,
        max_length=300,
        description="Store address shown on PDF receipts e.g. '14 Rumuola Road, Port Harcourt'"
    )
    assistant_name: Optional[str] = Field(
        None,
        max_length=80,
        description="Custom persona name for the WhatsApp assistant e.g. 'Amara' or 'Chef Tunde'"
    )
    assistant_personality: Optional[str] = Field(
        None,
        description="Personality style: friendly_casual | professional | warm_enthusiastic"
    )
    delivery_enabled: Optional[bool] = Field(
        None,
        description="Whether this store offers delivery to customers"
    )
    delivery_fee: Optional[float] = Field(
        None,
        ge=0,
        description="Flat delivery fee in NGN. Only takes effect when delivery_enabled is true."
    )

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "name": "Updated Store Name",
                "whatsapp_number": "+2348023456789",
                "store_contact_number": "+2348087654321",
                "assistant_name": "Amara",
                "assistant_personality": "warm_enthusiastic",
                "delivery_enabled": True,
                "delivery_fee": 1500.00
            }
        }
    )


# =====================================================
# Store login schemas
# =====================================================
class ClientLoginRequest(BaseModel):
    """Body for POST /clients/login"""
    client_id: str = Field(..., description="Store ID (e.g. STAB1234)")
    password: str  = Field(..., description="Store dashboard password")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {"client_id": "STAB1234", "password": "securepass123"}
        }
    )


class ClientLoginResponse(BaseModel):
    """Returned on successful store login"""
    access_token: str
    token_type:   str = "bearer"
    client_id:    str
    store_name:   str
    merchant_id:  str


class ClientSetPassword(BaseModel):
    """Body for PATCH /clients/{id}/password — merchant sets/resets store password"""
    password: str = Field(..., min_length=6, description="New plain-text password (min 6 chars)")

    model_config = ConfigDict(
        json_schema_extra={"example": {"password": "newpass456"}}
    )


# =====================================================
# Basic Read (minimal data)
# =====================================================
class ClientRead(ClientBase):
    created_at: Optional[datetime] = Field(None, description="Client creation timestamp")
    operator_notify_phone: Optional[str] = Field(None, description="Operator WhatsApp number for notifications")
    address: Optional[str] = Field(None, description="Store address shown on PDF receipts")
    assistant_name: Optional[str] = Field(None, description="Custom persona name for the WhatsApp assistant")
    assistant_personality: Optional[str] = Field(None, description="Personality style")
    delivery_enabled: bool = Field(False, description="Whether this store offers delivery")
    delivery_fee: Optional[float] = Field(None, description="Flat delivery fee in NGN")
    has_login: bool = Field(False, description="Whether this store has a dashboard password set")
    client_changes_enabled: bool = Field(False, description="Whether the store can edit delivery/persona settings")

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "CL5678",
                "name": "Tech Store Lagos",
                "whatsapp_number": "+2348012345678",
                "store_contact_number": "+2348098765432",
                "merchant_id": "MR1234",
                "created_at": "2024-01-15T10:30:00Z",
                "address": "14 Rumuola Road, Port Harcourt",
                "assistant_name": "Amara",
                "assistant_personality": "warm_enthusiastic",
                "delivery_enabled": True,
                "delivery_fee": 1500.00,
                "has_login": True,
                "client_changes_enabled": False
            }
        }
    )


# =====================================================
# Full Output (with relationships)
# =====================================================
class ClientOut(ClientRead):
    """Client response with WhatsApp credential included"""
    whatsapp_credential: Optional[ClientWhatsAppCredentialSimple] = Field(
        None,
        description="Client's WhatsApp credential (1:1 relationship)"
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "CL5678",
                "name": "Tech Store Lagos",
                "whatsapp_number": "+2348012345678",
                "store_contact_number": "+2348098765432",
                "merchant_id": "MR1234",
                "created_at": "2024-01-15T10:30:00Z",
                "delivery_enabled": True,
                "delivery_fee": 1500.00,
                "has_login": True,
                "whatsapp_credential": {
                    "phone_number_id": "123***345",
                    "whatsapp_number": "+15551234567",
                    "active": True,
                    "verified": True
                }
            }
        }
    )


# =====================================================
# Client with Credential Create (for convenience)
# =====================================================
class ClientWithCredentialCreate(BaseModel):
    """Create a client along with their WhatsApp credential in one request"""
    client: ClientCreate
    credential: Optional[ClientWhatsAppCredentialCreate] = Field(
        None,
        description="Optional WhatsApp credential to create along with client"
    )

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "client": {
                    "id": "CL5678",
                    "name": "Tech Store Lagos",
                    "whatsapp_number": "+2348012345678",
                    "store_contact_number": "+2348098765432",
                    "merchant_id": "MR1234"
                },
                "credential": {
                    "client_id": "CL5678",
                    "phone_number_id": "123456789012345",
                    "token": "EAADAZCZBPZB...",
                    "active": True,
                    "whatsapp_number": "+15551234567"
                }
            }
        }
    )


# =====================================================
# List/Summary Response
# =====================================================
class ClientSummary(BaseModel):
    """Summary view for listing clients"""
    id: str
    name: str
    whatsapp_number: Optional[str] = None
    store_contact_number: Optional[str] = None
    merchant_id: str
    created_at: Optional[datetime]
    operator_notify_phone: Optional[str] = Field(None, description="Operator WhatsApp number")
    address: Optional[str] = Field(None, description="Store address")
    assistant_name: Optional[str] = Field(None, description="Custom persona name")
    assistant_personality: Optional[str] = Field(None, description="Personality style")
    delivery_enabled: bool = Field(False, description="Whether this store offers delivery")
    delivery_fee: Optional[float] = Field(None, description="Flat delivery fee in NGN")
    has_whatsapp_credential: bool = Field(False, description="Whether client has a WhatsApp credential")
    whatsapp_active: Optional[bool] = Field(None, description="Whether credential is active")
    has_login: bool = Field(False, description="Whether this store has a dashboard password set")
    client_changes_enabled: bool = Field(False, description="Whether the store can edit delivery/persona settings")

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "CL5678",
                "name": "Tech Store Lagos",
                "whatsapp_number": "+2348012345678",
                "merchant_id": "MR1234",
                "created_at": "2024-01-15T10:30:00Z",
                "operator_notify_phone": "2348012345678",
                "delivery_enabled": True,
                "delivery_fee": 1500.00,
                "has_whatsapp_credential": True,
                "whatsapp_active": True,
                "has_login": True,
                "client_changes_enabled": False
            }
        }
    )
